import { describe, expect, it } from 'vitest'
import { EMPTY_CELL, isBlankExisting, planUpsert, summariseColumnImpact } from './importPlan'
import type { PlanOptions, Strategy } from './importPlan'

const RECORD_BLANKNESS = {
  apiName: 'text',
  label: 'text',
  externalId: 'text',
  description: 'text',
  moduleId: 'ref',
  origin: 'text',
  isDeprecated: 'value',
} as const

const opts = (
  strategy: Strategy,
  columns: string[],
  extra: Partial<PlanOptions> = {},
): PlanOptions => ({
  strategy,
  columns: new Set(columns),
  blankness: RECORD_BLANKNESS,
  ...extra,
})

const existingRecord = {
  apiName: 'Account',
  label: 'Account',
  externalId: '01I000',
  description: 'A customer organisation, carefully written by a human.',
  moduleId: 'mod-sales',
  origin: 'native',
  isDeprecated: false,
}

describe('create', () => {
  it('takes every provided column plus defaults', () => {
    const plan = planUpsert(
      null,
      { apiName: 'Invoice', label: 'Invoice' },
      opts('fill-blanks', ['apiName', 'label'], { defaults: { origin: 'custom' } }),
    )
    expect(plan.action).toBe('create')
    expect(plan.values).toEqual({ apiName: 'Invoice', label: 'Invoice', origin: 'custom' })
  })

  it('ignores empty cells rather than writing empty strings', () => {
    const plan = planUpsert(
      null,
      { apiName: 'Invoice', label: 'Invoice', description: EMPTY_CELL },
      opts('fill-blanks', ['apiName', 'label', 'description']),
    )
    expect(plan.values).not.toHaveProperty('description')
  })
})

describe('a column the file does not have', () => {
  it('cannot change anything, even under overwrite', () => {
    // The sparse-CSV disaster: a file with only two columns must not touch the rest.
    const plan = planUpsert(
      existingRecord,
      { apiName: 'Account', description: 'Replaced.' },
      opts('overwrite', ['apiName', 'description']),
    )
    expect(plan.changes.map((c) => c.column)).toEqual(['description'])
    expect(plan.values).not.toHaveProperty('label')
    expect(plan.values).not.toHaveProperty('isDeprecated')
    expect(plan.values).not.toHaveProperty('origin')
  })

  it('cannot change anything even when a value is passed for it', () => {
    // Defence in depth: a stray key outside the header set is still ignored.
    const plan = planUpsert(
      existingRecord,
      { apiName: 'Account', label: 'Sneaky' },
      opts('overwrite', ['apiName']),
    )
    expect(plan.action).toBe('unchanged')
  })
})

describe('fill-blanks', () => {
  it('fills a column the catalog has nothing in', () => {
    const plan = planUpsert(
      { ...existingRecord, description: null },
      { description: 'From the source system' },
      opts('fill-blanks', ['description']),
    )
    expect(plan.action).toBe('update')
    expect(plan.changes).toEqual([
      { column: 'description', before: null, after: 'From the source system' },
    ])
  })

  it('treats an empty string in the catalog as blank', () => {
    const plan = planUpsert(
      { ...existingRecord, description: '   ' },
      { description: 'Filled' },
      opts('fill-blanks', ['description']),
    )
    expect(plan.action).toBe('update')
  })

  it('never overwrites prose someone wrote, and reports the disagreement', () => {
    const plan = planUpsert(
      existingRecord,
      { description: 'Generic autogenerated text' },
      opts('fill-blanks', ['description']),
    )
    expect(plan.action).toBe('unchanged')
    expect(plan.suppressed).toEqual([
      {
        column: 'description',
        existing: existingRecord.description,
        incoming: 'Generic autogenerated text',
      },
    ])
  })

  it('cannot flip a boolean, because false is a value and not a hole', () => {
    // If `false` counted as blank this would be an overwrite wearing a fill-blanks
    // badge — every false in the catalog flipped by any file carrying the column.
    const plan = planUpsert(
      existingRecord,
      { isDeprecated: true },
      opts('fill-blanks', ['isDeprecated']),
    )
    expect(plan.action).toBe('unchanged')
    expect(plan.suppressed[0]?.column).toBe('isDeprecated')
  })

  it('can still update and suppress in the same row', () => {
    const plan = planUpsert(
      { ...existingRecord, externalId: null },
      { externalId: '01I999', description: 'Would clobber' },
      opts('fill-blanks', ['externalId', 'description']),
    )
    expect(plan.action).toBe('update')
    expect(plan.changes).toHaveLength(1)
    expect(plan.suppressed).toHaveLength(1)
  })
})

describe('overwrite', () => {
  it('replaces a value that differs', () => {
    const plan = planUpsert(
      existingRecord,
      { label: 'Customer' },
      opts('overwrite', ['label']),
    )
    expect(plan.changes).toEqual([
      { column: 'label', before: 'Account', after: 'Customer' },
    ])
  })

  it('does not clear a value with an empty cell by default', () => {
    // In CSV "clear this" and "I have no data" are the same bytes.
    const plan = planUpsert(
      existingRecord,
      { description: EMPTY_CELL },
      opts('overwrite', ['description']),
    )
    expect(plan.action).toBe('unchanged')
  })

  it('clears only when explicitly asked to', () => {
    const plan = planUpsert(
      existingRecord,
      { description: EMPTY_CELL },
      opts('overwrite', ['description'], { emptyCellsClear: true }),
    )
    expect(plan.changes).toEqual([
      { column: 'description', before: existingRecord.description, after: null },
    ])
  })

  it('will not clear a column the row must have a value in', () => {
    const plan = planUpsert(
      existingRecord,
      { isDeprecated: EMPTY_CELL },
      opts('overwrite', ['isDeprecated'], { emptyCellsClear: true }),
    )
    expect(plan.action).toBe('unchanged')
  })
})

describe('create-only', () => {
  it('skips an existing row and says why', () => {
    const plan = planUpsert(
      existingRecord,
      { description: 'Anything' },
      opts('create-only', ['description']),
    )
    expect(plan.action).toBe('skip')
    expect(plan.reason).toMatch(/only adds new rows/)
  })
})

describe('unchanged and skip stay distinct', () => {
  it('reports unchanged when the file simply agrees', () => {
    const plan = planUpsert(
      existingRecord,
      { label: 'Account' },
      opts('overwrite', ['label']),
    )
    expect(plan.action).toBe('unchanged')
    expect(plan.suppressed).toEqual([])
  })

  it('reports unchanged with suppression when the file disagreed and we declined', () => {
    const plan = planUpsert(
      existingRecord,
      { label: 'Something else' },
      opts('fill-blanks', ['label']),
    )
    expect(plan.action).toBe('unchanged')
    expect(plan.suppressed).toHaveLength(1)
  })
})

describe('protected columns', () => {
  it('never changes a protected column implicitly, but reports the attempt', () => {
    const plan = planUpsert(
      existingRecord,
      { apiName: 'Account_v2' },
      opts('overwrite', ['apiName'], { protectedColumns: new Set(['apiName']) }),
    )
    expect(plan.action).toBe('unchanged')
    expect(plan.suppressed).toEqual([
      { column: 'apiName', existing: 'Account', incoming: 'Account_v2' },
    ])
  })
})

describe('value comparison', () => {
  it('treats null and empty string in the catalog as the same absence', () => {
    const plan = planUpsert(
      { ...existingRecord, description: null },
      { description: EMPTY_CELL },
      opts('overwrite', ['description'], { emptyCellsClear: true }),
    )
    expect(plan.action).toBe('unchanged')
  })

  it('compares option arrays by content, not identity', () => {
    const plan = planUpsert(
      { options: ['a', 'b'] },
      { options: ['a', 'b'] },
      {
        strategy: 'overwrite',
        columns: new Set(['options']),
        blankness: { options: 'value' },
      },
    )
    expect(plan.action).toBe('unchanged')
  })
})

describe('isBlankExisting', () => {
  it('never calls a boolean blank', () => {
    expect(isBlankExisting(false, 'value')).toBe(false)
    expect(isBlankExisting(0, 'value')).toBe(false)
  })

  it('calls null blank for a reference', () => {
    expect(isBlankExisting(null, 'ref')).toBe(true)
    expect(isBlankExisting('', 'ref')).toBe(false)
  })

  it('calls null and whitespace blank for text', () => {
    expect(isBlankExisting(null, 'text')).toBe(true)
    expect(isBlankExisting('  ', 'text')).toBe(true)
    expect(isBlankExisting('x', 'text')).toBe(false)
  })
})

describe('summariseColumnImpact', () => {
  it('counts rows per column, busiest first', () => {
    const impact = summariseColumnImpact([
      { entity: 'field', plan: planUpsert(null, {}, opts('overwrite', [])) },
      {
        entity: 'field',
        plan: {
          action: 'update',
          values: {},
          suppressed: [],
          changes: [
            { column: 'description', before: null, after: 'a' },
            { column: 'label', before: 'x', after: 'y' },
          ],
        },
      },
      {
        entity: 'field',
        plan: {
          action: 'update',
          values: {},
          suppressed: [],
          changes: [{ column: 'description', before: null, after: 'b' }],
        },
      },
    ])
    expect(impact).toEqual([
      { entity: 'field', column: 'description', rows: 2 },
      { entity: 'field', column: 'label', rows: 1 },
    ])
  })
})
